package gamelogic.game;

public enum GameEvent {
    SELECTED_TRAIN,
    SELECTED_MULTIPLE_TRAIN_CANCEL(0),
    SELECTED_TRAIN_DISCARD_TRAIN,
    SELECTED_TRAIN_CANCEL(0),
    CANCEL_PLACE_TRAIN(0),
    CANCEL_REROUTE_TRAIN_DIALOG(0),
    SELECTED_STATION,
    ROUTING_BEGIN,
    ROUTING_DISCARD_TRAIN,
    ROUTING_DONE,
    ROUTING_CANCEL(0),
    END_TURN(3),
    BROKEN_JUNCTION(0),
    ADD_GOAL(0),
    ADD_TRAIN(0),
    ADD_CONNECTION(0),
    SELECTED_GOAL,
    SELECTED_GOAL_DISCARD,
    SELECTED_GOAL_CANCEL(0),
    NEW_CONNECTION_MODE_BEGIN,
    NEW_CONNECTION_MODE_CONFIRM_NEW,
    NEW_CONNECTION_MODE_SELECT_MATERIAL,
    NEW_CONNECTION_MODE_SELECT_MATERIAL_CANCEL(0),
    NEW_CONNECTION_MODE_EXIT,
    SELECTED_CONNECTION,
    SELECTED_CONNECTION_CANCEL(0),
    SELECTED_CONNECTION_REPAIR,
    SELECTED_CONNECTION_REPAIR_SELECT_AMOUNT,
    SELECTED_CONNECTION_REPAIR_SELECT_AMOUNT_CANCEL(0),
    SELECTED_CONNECTION_UPGRADE,
    SELECTED_CONNECTION_UPGRADE_SELECT_MATERIAL,
    SELECTED_CONNECTION_UPGRADE_SELECT_MATERIAL_CANCEL(0),
    SELECTED_CONNECTION_REMOVE,
    SELECTED_CONNECTION_REMOVE_CONFIRM,
    SELECTED_CONNECTION_REMOVE_CANCEL(0),
    ;

    private static final float DEFAULT_DELAY = 1.5f;
    public float delay;

    GameEvent(float delay) {
        this.delay = delay;
    }

    GameEvent() {
        this.delay = DEFAULT_DELAY;
    }
}
