package gamelogic.game;

public enum GameEvent {
    CLICKED_TRAIN,
    CLICKED_PLACE_TRAIN,
    CLICKED_PLACE_TRAIN_DISCARD,
    CLICKED_PLACE_TRAIN_CANCEL,
    CLICKED_STATION,
    CLICKED_BEGIN_ROUTING,
    CLICKED_ROUTING_DISCARD_TRAIN,
    CLICKED_ROUTING_DONE,
    CLICKED_ROUTING_CANCEL,
    CLICKED_END_TURN(3),
    BROKEN_JUNCTION(0),
    ADD_GOAL(0),
    ADD_TRAIN(0),
    ADD_CONNECTION(0),
    CLICKED_GOAL_BUTTON,
    CLICKED_DISCARD_GOAL,
    CLICKED_DISCARD_GOAL_CANCEL,
    CLICKED_CONNECTION_BUTTON,
    CLICKED_CONNECTION_BUTTON_CANCEL,
    CLICKED_ADD_CONNECTION_MODE,
    CLICKED_ADD_CONNECTION_MODE_DONE,
    CLICKED_NEW_CONNECTION,
    CLICKED_CHOOSE_NEW_CONNECTION_MATERIAL,
    CLICKED_CHOOSE_NEW_CONNECTION_MATERIAL_CANCEL,
    CLICKED_REPAIR_CONNECTION,
    CLICKED_CHOOSE_REPAIR_CONNECTION_AMOUNT,
    CLICKED_CHOOSE_REPAIR_CONNECTION_AMOUNT_CANCEL,
    CLICKED_UPGRADE_CONNECTION,
    CLICKED_CHOOSE_UPGRADE_CONNECTION_MATERIAL,
    CLICKED_CHOOSE_UPGRADE_CONNECTION_MATERIAL_CANCEL,
    CLICKED_REMOVE_CONNECTION,
    CLICKED_CHOOSE_REMOVE_CONNECTION,
    CLICKED_CHOOSE_REMOVE_CONNECTION_CANCEL,
    ;

    private static final float DEFAULT_DELAY = 1.5f;
    public float delay;

    GameEvent(float delay) {
        this.delay = delay;
    }

    GameEvent() {
        this.delay = DEFAULT_DELAY;
    }
}
